const CC_BY_4 = "CC BY 4.0";
const CC0 = "CC0 (public domain)";
const GENERATED = "AI-generated / AI-assisted; no third-party licence attaches";

/**
 * Concise in-game counterpart of docs/ASSETS_AND_CREDITS.md.
 *
 * This registry only states provenance that the repository currently supports.
 * Unknown or incomplete provenance is surfaced explicitly rather than guessed.
 */
export const CREDITS = [
  {
    heading: "Project team",
    entries: [
      {
        name: "7:55AM — At Wits End",
        detail: "COMS3006A / COMS3025A Computer Graphics and Visualisation project (Wits Commute Simulator)."
      },
      {
        name: "Team",
        detail: "Dean Feldman, Shayna Unterslak, Nadav Sundy, Liora Rosenberg, Benjamin Swartz and Gabriel Raz."
      }
    ]
  },
  {
    heading: "Libraries and type",
    entries: [
      {
        name: "Three.js",
        detail: "3D rendering, cameras, scene graph, materials and WebGL abstraction — MIT.",
        url: "https://threejs.org"
      },
      {
        name: "Vite",
        detail: "Development server and production bundling — MIT.",
        url: "https://vitejs.dev"
      },
      {
        name: "Pixelify Sans",
        detail: "Google Fonts typeface by Stefie Justprince — SIL Open Font License 1.1.",
        url: "https://fonts.google.com/specimen/Pixelify+Sans"
      }
    ]
  },
  {
    heading: "CC BY 4.0 models",
    entries: [
      {
        name: "Whiteboard",
        detail: `tboiston — ${CC_BY_4}. Level 3 classroom; rescaled and repositioned at runtime.`,
        url: "https://sketchfab.com/3d-models/whiteboard-d0b05bd140734a799666f0a29e1fe1bb"
      },
      {
        name: "Plastic Chair",
        detail: `Jazavac — ${CC_BY_4}. Level 3 classroom seating; rescaled and repeated across the room.`,
        url: "https://sketchfab.com/3d-models/plastic-chair-be3d5131e634424e89ffd57ebb19804e"
      },
      {
        name: "Paper Tablet",
        detail: `NameSsis — ${CC_BY_4}. Level 3 answer tablets; rescaled and given runtime answer textures.`,
        url: "https://sketchfab.com/3d-models/paper-tablet-f2b7978367164eb38167dd4832978288"
      },
      {
        name: "Car Scene",
        detail: `toivo — ${CC_BY_4}. Level 1 player car; the showcase surroundings are removed at load time.`,
        url: "https://sketchfab.com/3d-models/car-scene-b7b32eaca80d460c9338197e2c9d1408"
      },
      {
        name: "Generic Passenger Car Pack",
        detail: `Comrade1280 — ${CC_BY_4}. Level 1 parked-car population; individual vehicles are extracted and cloned.`,
        url: "https://sketchfab.com/3d-models/generic-passenger-car-pack-20f9af9b8a404d5cb022ac6fe87f21f5"
      }
    ]
  },
  {
    heading: "Textures and environment lighting",
    entries: [
      {
        name: "Asphalt 02 PBR set",
        detail: `Rob Tuytel / Poly Haven — ${CC0}. Diffuse, roughness, displacement and OpenGL normal textures used by the Level 1 and Level 2 asphalt shader.`,
        url: "https://polyhaven.com/a/asphalt_02"
      },
      {
        name: "Joburg Central Sunset HDRI",
        detail: `Dimitrios Savva (photography) and Greg Zaal (processing) / Poly Haven — ${CC0}. Used for Level 3 environment lighting and background.`,
        url: "https://polyhaven.com/a/sunset_jhbcentral"
      }
    ]
  },
  {
    heading: "Original music",
    entries: [
      {
        name: "Commute Theme / Dusk Drive / Empire Rush / Don't Get Caught",
        detail: `OpenAI-assisted original compositions generated for this project on 2026-09-25 and stored as pre-rendered WAV files. ${GENERATED}. No third-party samples are recorded as used.`
      }
    ]
  },
  {
    heading: "AI-generated and project-created assets",
    entries: [
      {
        name: "Level 1 story loading screen",
        detail: `Generated with OpenAI image generation on 2026-09-08 from the team's driver-checking-a-watch concept reference — ${GENERATED}.`
      },
      {
        name: "Classroom brick wall and terrazzo floor",
        detail: `Generated by Gabriel Raz and tiled at runtime in Level 3 — ${GENERATED}.`
      },
      {
        name: "Level 3 zoom-hands UI",
        detail: `Generated by Gabriel Raz with OpenAI gpt-image v2.0; C2PA metadata records trainedAlgorithmicMedia — ${GENERATED}.`
      },
      {
        name: "Cartoon Desk",
        detail: "Authored for the project in Blender by Gabriel Raz with Claude assistance; project-owned."
      },
      {
        name: "Team-authored systems and environments",
        detail: "Includes the parking blockout and bay layout, surrounding road geometry, vehicle rig/controller, custom shader code, Level 2 crossing/traffic layout, Level 3 classroom layout and exam-paper textures, and shared UI/menu/HUD styling."
      }
    ]
  },
  {
    heading: "Pending provenance before final submission",
    entries: [
      {
        name: "Normalised vehicle variants",
        detail: "Aston Martin, BYD, Honda, Nissan and Volkswagen runtime variants were converted from uploaded archives that did not preserve original source, author or licence metadata. Supply those records or replace the assets."
      },
      {
        name: "Diesel Thomas proxy",
        detail: "The runtime mesh is a project-made procedural proxy, but the underlying character reference still needs rights clearance or removal."
      },
      {
        name: "Level 1 recorded audio",
        detail: "car-crash.mp3, car-door-shut.mp3, idle-car.wav and collision-hit.mp3 still need complete source/author/licence records or replacement."
      },
      {
        name: "Pencil Pete trial font",
        detail: "pencil-pete-trial.ttf is loaded by Level 3 but its source and redistribution licence are not yet recorded."
      },
      {
        name: "Foliage and environment assets",
        detail: "The runtime foliage packs, stylized grass texture set and east precast-wall texture are used in Level 1 but still need source/licence or team-authorship records."
      },
      {
        name: "Level 2 character assets",
        detail: "Student backpack, NPC/player GLB/FBX models and walk/run/idle animations are used at runtime but their source/licence or team-authorship records are not yet complete."
      },
      {
        name: "Level 3 character/prop assets",
        detail: "Tutor GLB/FBX assets, the seated-student animation, classroom-desk and classroom-plastic-chair variants still need complete provenance records."
      },
      {
        name: "Wits shark",
        detail: "wits-shark.glb and wits-shark.png still need a source/licence or team-authorship record."
      },
      {
        name: "AMIC / road image textures",
        detail: "amic-fence.png, amic-fence-reference.png and 2695c241-17bb-416d-9d1d-7f061ccf7976.png still need source/licence or team-authorship records."
      },
      {
        name: "UI artwork still awaiting provenance records",
        detail: "at-wits-end-logo-v2.png, main-menu-background.png, main-menu-v3-background.png, level2-story-loading-screen.png, level3-story-loading-screen.png and suspicion-meter.png need generation records or source/licence records where not already documented."
      }
    ]
  }
];
